# Generated by Django 6.0.1 on 2026-01-29 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydarood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todaydata',
            old_name='username',
            new_name='name',
        ),
    ]
