# Generated by Django 6.0.1 on 2026-01-29 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydarood', '0002_rename_username_todaydata_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todaydata',
            old_name='name',
            new_name='eventDate',
        ),
    ]
