# Generated by Django 6.0.1 on 2026-01-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydarood', '0003_rename_name_todaydata_eventdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todaydata',
            name='date',
        ),
        migrations.AddField(
            model_name='todaydata',
            name='name',
            field=models.CharField(default='Muhammad Ali'),
        ),
        migrations.AlterField(
            model_name='todaydata',
            name='eventDate',
            field=models.DateField(),
        ),
    ]
